export const RESET_ALL = "RESET_ALL";
export const DOWNLOADING_FILE = "DOWNLOADING_FILE";
export const FILE_DOWNLOADED = "FILE_DOWNLOADED";
export const ERROR_DOWNLOADING = "ERROR_DOWNLOADING";
export const ERROR_SERVER = "ERROR_SERVER";

/* ACADEMIES */
export const LOADING_ACADEMIES = 'LOADING_ACADEMIES';
export const RECEIVE_ACADEMIES = 'RECEIVE_ACADEMIES';
export const ERROR_ACADEMY = 'ERROR_ACADEMY';
export const RECEIVE_ALL_ACADEMIES = 'RECEIVE_ALL_ACADEMIES';
export const RECEIVE_IMPORTEDYEARS ='RECEIVE_IMPORTEDYEARS';

/* CONSTAT */
export const LOADER_CONSTATS = 'LOADER_CONSTATS';
export const LOADER_CONSTATS_DONE = 'LOADER_CONSTATS_DONE';
export const ERROR_CONSTAT = 'ERROR_CONSTAT';
export const RECEIVE_CONSTATS = 'RECEIVE_CONSTATS';
export const RECEIVE_SELECTED_CONSTAT = 'RECEIVE_SELECTED_CONSTAT';
export const RECEIVE_CONSTAT_VARIABLE_OPENED = 'RECEIVE_CONSTAT_VARIABLE_OPENED';
export const DELETED_CONSTAT = 'DELETED_CONSTAT';
export const EXPORTED_CONSTAT = 'EXPORTED_CONSTAT';
export const RECEIVE_CONSTAT_VARIABLE_WITH_CHILDREN_OPENED = 'RECEIVE_CONSTAT_VARIABLE_WITH_CHILDREN_OPENED';
export const CREATED_CONSTAT = 'CREATED_CONSTAT';
export const RECEIVED_CALCULMERES_CONSTAT = 'RECEIVED_CALCULMERES_CONSTAT';
export const RECEIVED_CONSTAT_PROPRIETES = 'RECEIVED_CONSTAT_PROPRIETES';
export const SAVE_CONSTAT = 'SAVE_CONSTAT';
export const RECEIVE_ARCHIVED_CONSTAT='RECEIVE_ARCHIVED_CONSTAT';

/* SCENARIO */
export const LOADER_SCENARIO = 'LOADER_SCENARIO';
export const ERROR_SCENARIO = 'ERROR_SCENARIO';
export const RECEIVE_SCENARIOS = 'RECEIVE_SCENARIOS';
export const RECEIVE_SELECTED_SCENARIO = 'RECEIVE_SELECTED_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';
export const RECEIVE_SCENARIO_VARIABLE_OPENED = 'RECEIVE_SCENARIO_VARIABLE_OPENED';
export const RECEIVE_SCENARIO_VARIABLE_WITH_CHILDREN_OPENED = 'RECEIVE_SCENARIO_VARIABLE_WITH_CHILDREN_OPENED';
export const RECEIVE_SCENARIO_VARIABLE_MULTIPLE_WITH_CHILDREN_OPENED = 'RECEIVE_SCENARIO_VARIABLE_MULTIPLE_WITH_CHILDREN_OPENED';
export const CHANGE_DEGRE_SCENARIO = 'CHANGE_DEGRE_SCENARIO';
export const RECEIVE_FILIERES= 'RECEIVE_FILIERES';
export const SCENARIO_RECONDUIRE_VARIABLE_DONE = 'SCENARIO_RECONDUIRE_VARIABLE_DONE';
export const SCENARIO_RECONDUIRE_VARIABLES_DONE = 'SCENARIO_RECONDUIRE_VARIABLES_DONE';
export const SCENARIO_CALCUL_CONTEXTE_DONE = 'SCENARIO_CALCUL_CONTEXTE_DONE';
export const EXPORTED_SCENARIO = 'EXPORTED_SCENARIO';
export const CREATED_SCENARIO = 'CREATED_SCENARIO';
export const RECEIVED_CALCULMERES_SCENARIO = 'RECEIVED_CALCULMERES_SCENARIO';
export const RECEIVE_ARCHIVED_SCENARIO='RECEIVE_ARCHIVED_SCENARIO';
export const LOADING_SCENARIO_DONE = 'LOADING_SCENARIO_DONE';
export const RECEIVED_SCENARIO_PROPRIETES = 'RECEIVED_SCENARIO_PROPRIETES';
export const SCENARIO_RENAMED = 'SCENARIO_RENAMED';
export const SCENARION_CALCUL_ALL_DONE = 'SCENARION_CALCUL_ALL_DONE';

/* INFORMATION */
export const INFORMATION_ERROR = 'INFORMATION_ERROR';
export const CLEAR_INFORMATION = 'CLEAR_INFORMATION';
export const INFORMATION_SUCCESS = 'INFORMATION_SUCCESS';

/** RECAPITULATIF */
export const LOADING_RECAPITULATIFS = 'LOADIN_RECAPITULATIF'
export const RECEIVE_RECAPITULATIFS = 'RECEIVE_RECAPITULATIF'
export const LOADING_SELECTED_RECAPITULATIF = 'LOADING_SELECTED_RECAPITULATIF';
export const RECEIVE_SELECTED_RECAPITULATIF = 'RECEIVE_SELECTED_RECAPITULATIF';
export const LOADING_OPENING_VARIABLE_RECAPITULATIF = 'LOADING_OPENING_VARIABLE_RECAPITULATIF';
export const RECEIVE_CONSTAT_VARIABLE_OPENED_RECAPITULATIF = 'RECEIVE_CONSTAT_VARIABLE_OPENED_RECAPITULATIF';
export const ERROR_RECAPITULATIF = 'ERROR_RECAPITULATIF';
export const DELETE_RECAPITULATIF = 'DELETE_RECAPITULATIF';
export const EXPORTED_RECAPITULATIF = 'EXPORTED_RECAPITULATIF';
export const CREATED_RECAP='CREATED_RECAP';
export const RECEIVE_ARCHIVED_RECAP='RECEIVE_ARCHIVED_RECAP'
export const RECAP_CREATED='RECAP_CREATED'

/** IMPORT */
export const LOADER_IMPORT = 'LOADER_IMPORT';
export const ERROR_IMPORT = 'ERROR_IMPORT';
export const SUCCES_IMPORT = 'SUCCES_IMPORT';

/** USER */
export const LOADER_USER = 'LOADER_USER';
export const CREATE_USER = 'CREATE_USER';
export const ERROR_USER = 'ERROR_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const RECEIVE_ACADEMIES_USER = 'RECEIVE_ACADEMIES_USER';
export const RECEIVE_COLORS ='RECEIVE_COLORS';
export const LOADER_USER_DONE ='LOADER_USER_DONE';
export const RECEIVE_EXPORT_OPTION = 'RECEIVE_EXPORT_OPTION';

/** USER GUIDE */
export const RECEIVE_USER_GUIDE_NAME = 'RECEIVE_USER_GUIDE_NAME';

/**ARCHIVE */
export const LOADER_ARCHIVE='LOADER_ARCHIVE';
export const SUCCES_ARCHIVED='SUCCES_ARCHIVED';
export const ERROR_ARCHIVED='ERROR_ARCHIVED';

/** APPINFO */
export const RECEIVE_APP_INFO = 'RECEIVE_APP_INFO';
export const UPDATE_APP_INFO = 'UPDATE_APP_INFO';
export const LOADING_APP_INFO = 'LOADING_APP_INFO';